"""acceptance-entrypoint-generator: JSON IR -> pytest acceptance entry points.

Implements the Acceptance Pipeline Specification entrypoint-generator contract:

    acceptance-entrypoint-generator <json-ir> <generated-test-output>

Exit codes: 0 success, 1 input/output/generation error, 2 wrong usage.

Generated entry points embed the scenario execution structure derived from the
IR and load the JSON IR at runtime (default: the IR path supplied at
generation time; override with the ACCEPTANCE_IR environment variable). The
runtime path is what lets the gherkin mutator run the same generated entry
points against mutated IR without regenerating them.

Metadata (``<out>/metadata/<slug>.json``) carries the implementation hash
computed from generated acceptance files only, per the generator spec.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path

from acceptance.runtime import InvalidValueError, expand, load_ir

GENERATOR_VERSION = "1"
TEST_SUFFIX = "_acceptance_test.py"
USAGE = "usage: acceptance-entrypoint-generator <json-ir> <generated-test-output>"
SCHEMA_VERSION = 1
HASH_SCOPE = "generated_files"

# The IR does not carry its source feature path, so the generator recovers it
# from ACCEPTANCE_FEATURE_PATH when the pipeline knows it, and otherwise falls
# back to the project convention: features/<ir-basename>.feature.
FEATURE_PATH_ENV = "ACCEPTANCE_FEATURE_PATH"
FEATURES_DIR = "features"

_TEST_TEMPLATE = '''\
# Generated by acceptance-entrypoint-generator v{VERSION} (improve-my-sound).
# Do not edit by hand; regenerate from JSON IR.
"""Acceptance test entry points for: {feature_name}.

Source feature: {feature_path}
IR: {ir_path}
"""
from __future__ import annotations

import os

import acceptance.runtime as runtime
import acceptance.steps as steps

DEFAULT_IR_PATH = {ir_path!r}

# Scenario execution structure derived from the IR at generation time:
# (scenario_index, example_index, execution_name).
SCENARIO_EXECUTIONS = {executions!r}


def _load_ir():
    path = os.environ.get("ACCEPTANCE_IR", DEFAULT_IR_PATH)
    return runtime.load_ir(path)


def test_all_scenario_executions():
    ir = _load_ir()
    failures = []
    for scenario_index, example_index, _name in SCENARIO_EXECUTIONS:
        result = runtime.run_execution_by_index(
            ir, scenario_index, example_index, steps.REGISTRY
        )
        if not result.ok:
            failures.append(f"FAILED {{result.name}}: {{result.failure}}")
    assert not failures, "\\n\\n".join(failures)
'''


def slug(path: str) -> str:
    """Feature-metadata filename mapping per the generator spec: lowercase,
    runs of non-alphanumeric characters become one hyphen, hyphens trimmed."""
    out: list[str] = []
    hyphen = False
    for ch in path.lower():
        if ch.isalnum():
            out.append(ch)
            hyphen = False
        elif not hyphen and out:
            out.append("-")
            hyphen = True
    return "".join(out).strip("-")


def feature_path_from_ir(ir_path: str) -> str:
    """Recover the source feature path for ``ir_path``.

    Uses ACCEPTANCE_FEATURE_PATH when set (the pipeline knows the real path);
    otherwise applies the project convention features/<basename>.feature.
    """
    env_value = os.environ.get(FEATURE_PATH_ENV)
    if env_value:
        return env_value
    return f"{FEATURES_DIR}/{Path(ir_path).stem}.feature"


def executions_for(feature: dict) -> list[tuple[int, int, str]]:
    """The scenario execution structure: (scenario_index, example_index, name)."""
    return [
        (execution.scenario_index, execution.example_index, execution.name)
        for execution in expand(feature)
    ]


def _escape_path(text: str) -> str:
    """Escape backslashes so Windows paths survive Python source parsing."""
    return text.replace("\\", "\\\\")


def generated_test_text(
    feature: dict, ir_path: str, feature_path: str
) -> str:
    """Deterministic generated pytest entry point for one feature IR."""
    executions = executions_for(feature)
    return _TEST_TEMPLATE.format(
        VERSION=GENERATOR_VERSION,
        feature_name=feature["name"],
        feature_path=_escape_path(feature_path),
        ir_path=_escape_path(ir_path),
        executions=executions,
    )


def write_metadata(
    generated_dir: Path,
    feature_path: str,
    ir_path: str,
    test_relpath: str,
    test_bytes: bytes,
) -> Path:
    """Write the per-feature metadata file with the implementation hash."""
    metadata_dir = generated_dir / "metadata"
    metadata_dir.mkdir(parents=True, exist_ok=True)
    digest = hashlib.sha256(test_bytes).hexdigest()
    metadata = {
        "schema_version": SCHEMA_VERSION,
        "feature_path": feature_path,
        "ir_path": ir_path,
        "implementation_hash": f"sha256:{digest}",
        "hash_scope": HASH_SCOPE,
        "generated_files": [test_relpath],
    }
    metadata_path = metadata_dir / f"{slug(feature_path)}.json"
    metadata_path.write_text(
        json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return metadata_path


def generate(ir_path: str, generated_output: str) -> int:
    """Generate entry points for one IR; returns the process exit code."""
    try:
        feature = load_ir(ir_path)
    except InvalidValueError as exc:
        print(f"acceptance-entrypoint-generator: error: {exc}", file=sys.stderr)
        return 1

    feature_path = feature_path_from_ir(ir_path)
    out_dir = Path(generated_output)
    try:
        out_dir.mkdir(parents=True, exist_ok=True)
        test_text = generated_test_text(feature, ir_path, feature_path)
        test_name = f"{slug(feature_path)}{TEST_SUFFIX}"
        test_relpath = str(Path(generated_output) / test_name)
        test_path = out_dir / test_name
        test_path.write_text(test_text, encoding="utf-8")
        write_metadata(out_dir, feature_path, ir_path, test_relpath, test_text.encode("utf-8"))
        print(f"generated {test_relpath}")
        return 0
    except OSError as exc:
        print(f"acceptance-entrypoint-generator: error: {exc}", file=sys.stderr)
        return 1


def main(argv: list[str] | None = None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    if len(args) != 2:
        print(USAGE, file=sys.stderr)
        return 2
    return generate(args[0], args[1])


if __name__ == "__main__":
    sys.exit(main())
