#!/usr/bin/env python
"""voxera thin UI server (Tracks 7 + 8 + fase 3 vídeo).

Serves ui/ statically and exposes:

    POST /vote      {listener, clip_id, preferred, blind, mos_a, mos_b, comment}
                    -> appends one row to .auto/human/votes.csv
    POST /enhance   multipart file + preset -> runs the CLI (enhance/master/
                    restore/silence) and returns {url, report, stdout}
    POST /score     multipart file -> voxera score --format json
    POST /api/video/jobs   multipart file + model/fps/master -> async video job
    GET  /api/video/jobs/<id>  -> {status, progress, log, output_url}
    GET  /media/<file>  -> serves processed outputs (project-local)

Everything the UI renders is generated by the CLI (terminal-first premise).
Run (vídeo requiere el venv CUDA):
    .venv-video/Scripts/python.exe ui/server.py [port]
"""
from __future__ import annotations

import csv
import io
import json
import mimetypes
import os
import re
import subprocess
import sys
import tempfile
import threading
import time
import urllib.parse
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
UI_DIR = PROJECT_ROOT / "ui"
HUMAN_DIR = PROJECT_ROOT / ".auto" / "human"
MEDIA_DIR = PROJECT_ROOT / ".auto" / "human" / "media"
CONDITIONS_DIR = HUMAN_DIR / "conditions"
PAIRS_JSON = HUMAN_DIR / "pairs.json"
VOTES_CSV = HUMAN_DIR / "votes.csv"
CLI = [sys.executable, "-m", "voxera.cli"]
PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 8770

for d in (HUMAN_DIR, MEDIA_DIR):
    d.mkdir(parents=True, exist_ok=True)

if not VOTES_CSV.exists():
    VOTES_CSV.write_text(
        "listener,clip_id,preferred,blind,mos_a,mos_b,comment,timestamp\n", encoding="utf-8"
    )


# --- vídeo: jobs asíncronos (un enhance tarda minutos) ---------------------

JOBS: dict[str, dict] = {}
JOBS_LOCK = threading.Lock()


def _start_video_job(up: Path, model: str, fps: str, master: bool) -> str:
    job_id = uuid.uuid4().hex[:10]
    out = MEDIA_DIR / f"venh_{job_id}.mp4"
    job = {
        "id": job_id, "status": "running", "progress": 0.0,
        "done": 0, "total": 0, "log": [],
        "output": None, "error": None, "started": time.time(),
    }
    with JOBS_LOCK:
        JOBS[job_id] = job

    def _run():
        env = os.environ.copy()
        env["PYTHONPATH"] = str(PROJECT_ROOT / "src") + os.pathsep + str(PROJECT_ROOT)
        cmd = [sys.executable, "-m", "voxera.cli", "video", "enhance",
               str(up), "-o", str(out), "--model", model, "--fps", str(fps)]
        if master:
            cmd.append("--master-audio")
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, encoding="utf-8", errors="replace", env=env,
        )
        assert proc.stdout is not None
        for line in proc.stdout:
            line = line.rstrip()
            if not line:
                continue
            m = re.search(r"\[enhance\] (\d+)/(\d+)", line)
            if m:
                job["done"], job["total"] = int(m.group(1)), int(m.group(2))
                job["progress"] = job["done"] / max(job["total"], 1)
            m2 = re.search(r"\[extract\] (\d+) frames", line)
            if m2:
                job["total"] = int(m2.group(1))
            if len(job["log"]) < 200:
                job["log"].append(line)
        rc = proc.wait()
        job["log"].append(f"(exit {rc})")
        if rc == 0 and out.exists():
            job["status"], job["output"] = "done", f"/media/{out.name}"
        else:
            job["status"], job["error"] = "error", "\n".join(job["log"][-8:])

    threading.Thread(target=_run, daemon=True).start()
    return job_id


def _run_cli(args: list[str], timeout: int = 600) -> dict:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(PROJECT_ROOT / "src") + os.pathsep + str(PROJECT_ROOT)
    proc = subprocess.run(
        CLI + args, capture_output=True, text=True, env=env, timeout=timeout
    )
    return {"exit": proc.returncode, "stdout": proc.stdout, "stderr": proc.stderr}


def _boundary(headers) -> bytes:
    ctype = headers.get("Content-Type", "")
    for part in ctype.split(";"):
        part = part.strip()
        if part.startswith("boundary="):
            return part.split("=", 1)[1].strip('"').encode()
    return b""


def _file_body(part: bytes, boundary: bytes) -> tuple[bytes, bytes]:
    """(head, body) de una parte multipart — binary-safe.

    El corte por ``rsplit(\r\n, 2)`` es incorrecto para binario: los datos
    del fichero pueden contener CRLF y se pierden bytes (bug detectado con
    uploads mp4 truncados). Se corta en el ``\r\n--boundary`` de cierre.
    """
    head, _, body = part.partition(b"\r\n\r\n")
    marker = b"\r\n--" + boundary
    idx = body.rfind(marker)
    if idx != -1:
        body = body[:idx]
    return head, body


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):  # quieter
        pass

    def _send(self, code: int, body: bytes, ctype: str = "application/json"):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _json(self, obj, code: int = 200):
        self._send(code, json.dumps(obj, ensure_ascii=False).encode("utf-8"))

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        if path in ("/", "/index.html"):
            f = UI_DIR / "index.html"
        else:
            f = UI_DIR / path.lstrip("/")
        if f.is_file():
            self._send(200, f.read_bytes(), mimetypes.guess_type(str(f))[0] or "text/plain")
            return
        if path.startswith("/media/"):
            name = Path(path).name
            for base in (CONDITIONS_DIR, MEDIA_DIR):
                f = base / name
                if f.is_file():
                    ctype = mimetypes.guess_type(name)[0] or "application/octet-stream"
                    self._send(200, f.read_bytes(), ctype)
                    return
        if path.startswith("/api/video/jobs/"):
            job_id = Path(path).name
            with JOBS_LOCK:
                job = JOBS.get(job_id)
            if job is None:
                self._send(404, b"job not found", "text/plain")
                return
            self._json(job)
            return
        if path == "/pairs":
            if PAIRS_JSON.is_file():
                self._send(200, PAIRS_JSON.read_bytes())
                return
            self._send(200, b"[]")
            return
        self._send(404, b"not found", "text/plain")

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        try:
            if path == "/api/video/jobs":
                length = int(self.headers.get("Content-Length", 0))
                raw = self.rfile.read(length)
                boundary = _boundary(self.headers)
                model, fps, master, up = "animevideov3", "30", False, None
                for part in raw.split(b"--" + boundary):
                    if b'name="model"' in part:
                        model = part.partition(b"\r\n\r\n")[2].rsplit(b"\r\n", 1)[0].decode().strip() or model
                    if b'name="fps"' in part:
                        fps = part.partition(b"\r\n\r\n")[2].rsplit(b"\r\n", 1)[0].decode().strip() or fps
                    if b'name="master"' in part:
                        master = part.partition(b"\r\n\r\n")[2].rsplit(b"\r\n", 1)[0].decode().strip() == "1"
                    if b'name="file"' in part and b"filename=" in part:
                        head, body = _file_body(part, boundary)
                        fname = ""
                        for line in head.split(b"\r\n"):
                            if b"filename=" in line:
                                fname = line.split(b'filename="', 1)[1].rsplit(b'"', 1)[0].decode()
                        up = MEDIA_DIR / f"venh_upload_{int(time.time())}_{Path(fname).name}"
                        up.write_bytes(body)
                if up is None:
                    self._json({"ok": False, "error": "no file uploaded"}, 400)
                    return
                job_id = _start_video_job(up, model, fps, master)
                self._json({"ok": True, "job": job_id})
                return
            if path == "/vote":
                length = int(self.headers.get("Content-Length", 0))
                vote = json.loads(self.rfile.read(length) or b"{}")
                with open(VOTES_CSV, "a", newline="", encoding="utf-8") as fh:
                    csv.writer(fh).writerow([
                        vote.get("listener", "anon"),
                        vote.get("clip_id", "clip"),
                        vote.get("preferred", ""),
                        vote.get("blind", False),
                        vote.get("mos_a", ""),
                        vote.get("mos_b", ""),
                        vote.get("comment", ""),
                        time.strftime("%Y-%m-%dT%H:%M:%S"),
                    ])
                self._json({"ok": True, "rows": sum(1 for _ in open(VOTES_CSV, encoding="utf-8")) - 1})
                return
            if path == "/enhance":
                length = int(self.headers.get("Content-Length", 0))
                raw = self.rfile.read(length)
                boundary = _boundary(self.headers)
                preset, command, fname = "creator", "enhance", None
                for part in raw.split(b"--" + boundary):
                    if b'name="preset"' in part:
                        preset = part.partition(b"\r\n\r\n")[2].rsplit(b"\r\n", 1)[0].decode().strip() or "creator"
                    if b'name="command"' in part:
                        command = part.partition(b"\r\n\r\n")[2].rsplit(b"\r\n", 1)[0].decode().strip() or "enhance"
                    if b'name="file"' in part and b"filename=" in part:
                        head, body = _file_body(part, boundary)
                        for line in head.split(b"\r\n"):
                            if b"filename=" in line:
                                fname = line.split(b'filename="', 1)[1].rsplit(b'"', 1)[0].decode()
                        up = MEDIA_DIR / f"upload_{int(time.time())}_{Path(fname).name}"
                        up.write_bytes(body)
                if not fname:
                    self._json({"ok": False, "error": "no file uploaded"}, 400)
                    return
                # the CLI always writes WAV (48k/24-bit); video inputs produce mp4
                is_video = Path(fname).suffix.lower() in (".mp4", ".mov", ".mkv", ".webm", ".m4v")
                out_suffix = ".mp4" if is_video else ".wav"
                out = MEDIA_DIR / f"out_{int(time.time())}_{Path(up.name).stem}{out_suffix}"
                cmd = [command, str(up), "-o", str(out)]
                if command == "enhance":
                    cmd += ["--preset", preset]
                else:
                    cmd += ["--preset", preset]
                result = _run_cli(cmd)
                if result["exit"] != 0:
                    self._json({"ok": False, "error": result["stderr"] or result["stdout"]}, 500)
                    return
                score = _run_cli(["score", str(out), "--format", "json"], timeout=300)
                report = None
                if score["exit"] == 0:
                    try:
                        report = json.loads(score["stdout"])
                    except Exception:
                        report = None
                # score the ORIGINAL too, so the UI can show the before->after delta
                report_before = None
                score_before = _run_cli(["score", str(up), "--format", "json"], timeout=300)
                if score_before["exit"] == 0:
                    try:
                        report_before = json.loads(score_before["stdout"])
                    except Exception:
                        report_before = None
                self._json({"ok": True, "url": f"/media/{out.name}", "original": up.name,
                            "report": report, "report_before": report_before,
                            "stdout": result["stdout"]})
                return
            if path == "/score":
                length = int(self.headers.get("Content-Length", 0))
                raw = self.rfile.read(length)
                boundary = _boundary(self.headers)
                up = None
                for part in raw.split(b"--" + boundary):
                    if b'name="file"' in part and b"filename=" in part:
                        head, body = _file_body(part, boundary)
                        fname = ""
                        for line in head.split(b"\r\n"):
                            if b"filename=" in line:
                                fname = line.split(b'filename="', 1)[1].rsplit(b'"', 1)[0].decode()
                        up = MEDIA_DIR / f"score_{int(time.time())}_{Path(fname).name}"
                        up.write_bytes(body)
                if up is None:
                    self._json({"ok": False, "error": "no file"}, 400)
                    return
                result = _run_cli(["score", str(up), "--format", "json"], timeout=300)
                if result["exit"] != 0:
                    self._json({"ok": False, "error": result["stderr"]}, 500)
                    return
                self._json({"ok": True, "report": json.loads(result["stdout"])})
                return
        except Exception as exc:  # noqa: BLE001
            self._json({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)
            return
        self._send(404, b"not found", "text/plain")


if __name__ == "__main__":
    print(f"voxera UI en http://127.0.0.1:{PORT}  (votos -> {VOTES_CSV})")
    ThreadingHTTPServer(("127.0.0.1", PORT), Handler).serve_forever()
