#!/usr/bin/env python
"""voxera thin UI server (Tracks 7 + 8).

Serves ui/ statically and exposes:

    POST /vote      {listener, clip_id, preferred, blind, mos_a, mos_b, comment}
                    -> appends one row to .auto/human/votes.csv
    POST /enhance   multipart file + preset -> runs the CLI (enhance/master/
                    restore/silence) and returns {url, report, stdout}
    POST /score     multipart file -> voxera score --format json
    GET  /media/<file>  -> serves processed outputs (project-local)

Everything the UI renders is generated by the CLI (terminal-first premise).
Run:  .venv-ims/Scripts/python.exe ui/server.py [port]
"""
from __future__ import annotations

import csv
import io
import json
import mimetypes
import os
import subprocess
import sys
import tempfile
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
UI_DIR = PROJECT_ROOT / "ui"
HUMAN_DIR = PROJECT_ROOT / ".auto" / "human"
MEDIA_DIR = PROJECT_ROOT / ".auto" / "human" / "media"
VOTES_CSV = HUMAN_DIR / "votes.csv"
CLI = [sys.executable, "-m", "voxera.cli"]
PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 8770

for d in (HUMAN_DIR, MEDIA_DIR):
    d.mkdir(parents=True, exist_ok=True)

if not VOTES_CSV.exists():
    VOTES_CSV.write_text(
        "listener,clip_id,preferred,blind,mos_a,mos_b,comment,timestamp\n", encoding="utf-8"
    )


def _run_cli(args: list[str], timeout: int = 600) -> dict:
    env = os.environ.copy()
    env["PYTHONPATH"] = str(PROJECT_ROOT / "src") + os.pathsep + str(PROJECT_ROOT)
    proc = subprocess.run(
        CLI + args, capture_output=True, text=True, env=env, timeout=timeout
    )
    return {"exit": proc.returncode, "stdout": proc.stdout, "stderr": proc.stderr}


def _boundary(headers) -> bytes:
    ctype = headers.get("Content-Type", "")
    for part in ctype.split(";"):
        part = part.strip()
        if part.startswith("boundary="):
            return part.split("=", 1)[1].strip('"').encode()
    return b""


class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):  # quieter
        pass

    def _send(self, code: int, body: bytes, ctype: str = "application/json"):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _json(self, obj, code: int = 200):
        self._send(code, json.dumps(obj, ensure_ascii=False).encode("utf-8"))

    def do_GET(self):
        path = urllib.parse.urlparse(self.path).path
        if path in ("/", "/index.html"):
            f = UI_DIR / "index.html"
        else:
            f = UI_DIR / path.lstrip("/")
        if f.is_file():
            self._send(200, f.read_bytes(), mimetypes.guess_type(str(f))[0] or "text/plain")
            return
        if path.startswith("/media/"):
            f = MEDIA_DIR / Path(path).name
            if f.is_file():
                self._send(200, f.read_bytes(), "audio/wav")
                return
        self._send(404, b"not found", "text/plain")

    def do_POST(self):
        path = urllib.parse.urlparse(self.path).path
        try:
            if path == "/vote":
                length = int(self.headers.get("Content-Length", 0))
                vote = json.loads(self.rfile.read(length) or b"{}")
                with open(VOTES_CSV, "a", newline="", encoding="utf-8") as fh:
                    csv.writer(fh).writerow([
                        vote.get("listener", "anon"),
                        vote.get("clip_id", "clip"),
                        vote.get("preferred", ""),
                        vote.get("blind", False),
                        vote.get("mos_a", ""),
                        vote.get("mos_b", ""),
                        vote.get("comment", ""),
                        time.strftime("%Y-%m-%dT%H:%M:%S"),
                    ])
                self._json({"ok": True, "rows": sum(1 for _ in open(VOTES_CSV, encoding="utf-8")) - 1})
                return
            if path == "/enhance":
                length = int(self.headers.get("Content-Length", 0))
                raw = self.rfile.read(length)
                boundary = _boundary(self.headers)
                preset, command, fname = "creator", "enhance", None
                for part in raw.split(b"--" + boundary):
                    if b'name="preset"' in part:
                        preset = part.partition(b"\r\n\r\n")[2].rsplit(b"\r\n", 1)[0].decode().strip() or "creator"
                    if b'name="command"' in part:
                        command = part.partition(b"\r\n\r\n")[2].rsplit(b"\r\n", 1)[0].decode().strip() or "enhance"
                    if b'name="file"' in part and b"filename=" in part:
                        head, _, body = part.partition(b"\r\n\r\n")
                        for line in head.split(b"\r\n"):
                            if b"filename=" in line:
                                fname = line.split(b'filename="', 1)[1].rsplit(b'"', 1)[0].decode()
                        body = body.rsplit(b"\r\n", 2)[0]
                        up = MEDIA_DIR / f"upload_{int(time.time())}_{Path(fname).name}"
                        up.write_bytes(body)
                if not fname:
                    self._json({"ok": False, "error": "no file uploaded"}, 400)
                    return
                out = MEDIA_DIR / f"out_{int(time.time())}{up.suffix or '.wav'}"
                cmd = [command, str(up), "-o", str(out)]
                if command == "enhance":
                    cmd += ["--preset", preset]
                else:
                    cmd += ["--preset", preset]
                result = _run_cli(cmd)
                if result["exit"] != 0:
                    self._json({"ok": False, "error": result["stderr"] or result["stdout"]}, 500)
                    return
                score = _run_cli(["score", str(out), "--format", "json"], timeout=300)
                report = None
                if score["exit"] == 0:
                    try:
                        report = json.loads(score["stdout"])
                    except Exception:
                        report = None
                self._json({"ok": True, "url": f"/media/{out.name}", "report": report,
                            "stdout": result["stdout"]})
                return
            if path == "/score":
                length = int(self.headers.get("Content-Length", 0))
                raw = self.rfile.read(length)
                boundary = _boundary(self.headers)
                up = None
                for part in raw.split(b"--" + boundary):
                    if b'name="file"' in part and b"filename=" in part:
                        head, _, body = part.partition(b"\r\n\r\n")
                        fname = ""
                        for line in head.split(b"\r\n"):
                            if b"filename=" in line:
                                fname = line.split(b'filename="', 1)[1].rsplit(b'"', 1)[0].decode()
                        body = body.rsplit(b"\r\n", 2)[0]
                        up = MEDIA_DIR / f"score_{int(time.time())}_{Path(fname).name}"
                        up.write_bytes(body)
                if up is None:
                    self._json({"ok": False, "error": "no file"}, 400)
                    return
                result = _run_cli(["score", str(up), "--format", "json"], timeout=300)
                if result["exit"] != 0:
                    self._json({"ok": False, "error": result["stderr"]}, 500)
                    return
                self._json({"ok": True, "report": json.loads(result["stdout"])})
                return
        except Exception as exc:  # noqa: BLE001
            self._json({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)
            return
        self._send(404, b"not found", "text/plain")


if __name__ == "__main__":
    print(f"voxera UI en http://127.0.0.1:{PORT}  (votos -> {VOTES_CSV})")
    ThreadingHTTPServer(("127.0.0.1", PORT), Handler).serve_forever()
